### ISSUE TITLE
Trailing whitespace on Andstatus

### ISSUE THREAD

**Issue by chimo** [chimo/gs-markdown#10]
Because our markdown'ed notices are wrapped in a `p` tag, which has a margin-bottom.

**Comment by chimo** [comment]
Brainstorm: 
1. Remove add `<p>` tags
2. Replace all `</p>` tags with `<br><br>`
3. Remove trailing `<br><br>`

It's ugly, but it might work okay.

**Comment by faulteh** [comment]
Couldn't we change all <p> tags with a <p class="markdown-p"> or something like that after the Markdown transform has been done?

**Comment by blog2read** [comment]
Seems to be fixed.

**Comment by chimo** [comment]
(URL shortening/auto-linking documented in #11)
