### ISSUE TITLE
PHP error 500

### ISSUE THREAD

**Issue by blog2read** [chimo/gs-markdown#4]
Over here I get a php error 500:

`PHP Fatal error:  Call to undefined function common_remove_unicode_formatting() in /var/www/domain/public_html/plugins/Markdown/MarkdownPlugin.php on line 20, referer: `

**Comment by chimo** [comment]
Strange, this was added [9 months ago](https://git.gnu.io/gnu/gnu-social/commit/3dce6d9f6a1a95c42cdc1762140528323c71b08f#ed7359f737f7038f63b7a96043bb9239e4c5072e_579_591). Which version of GNU social are you running?
