### ISSUE TITLE
Paragraphs and Headings

### ISSUE THREAD

**Issue by faulteh** [chimo/gs-markdown#6]
So I was trying out a post that had multiple headings and paragraphs and it squished it all into a single line. 

It looks like that notices were getting their whitespace stripped by the "lib/util.php" function common_strip_html() in the Notice class.

There is a line about line 832 on classes/notice.php that is:

```php
$stored->content = common_strip_html($stored->rendered);
```

Which I changed to 

```php
$stored->content = common_strip_html($stored->rendered, true, true);
```

Which seemed to fix this issue. However this fix is outside the plugin so it's not the "correct" fix!

**Comment by chimo** [comment]
Hi!
Can you give the latest code a try? It seems to do the trick on my end.
