### ISSUE TITLE
Can the plugin be made to work in the profile section too?

### ISSUE THREAD

**Issue by stormdragon2976** [chimo/gs-markdown#6]
It would be great if you could also use markdown in the profile section of settings.

**Comment by chimo** [comment]
Just to make sure I understand, do you mean the "Bio" field of the profile:
![bio](https://user-images.githubusercontent.com/350505/29344426-cb922340-8205-11e7-8de2-0cf86bdcafdb.png)

And rendered here:
![bio2](https://user-images.githubusercontent.com/350505/29344747-095cacc0-8208-11e7-9a4a-41e57bc48eb7.png)

**Comment by stormdragon2976** [comment]
Yes, I meant the bio field. I am blind, so I cant see what is in the .png images, but if you look at [my bio](https://social.stormdragon.tk/storm), it is currently in unprocessed markdown.

**Comment by chimo** [comment]
Gotcha, I will have a look into it this week

**Comment by chimo** [comment]
I pushed some changes a couple of days ago. Let me know if this, and the "list" issue are fixed on your end

**Comment by stormdragon2976** [comment]
Both issues seem to be fixed. I can use lists, and my profile is properly formatted.
Thank you :)
